/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.HashMap;
import java.util.TreeSet;
import java.util.stream.Collectors;

public class App {
    

    public static void main(String[] args) {
        Database database = new Database(100);
    

        database.listOfItems().stream()
            .collect(Collectors.groupingBy(Item::getType, Collectors.counting())) 
            .forEach((k, v) -> System.out.println(k + ": " + v));
    }
}

