/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    

    public static void main(String[] args) {
        Database database = new Database(100);
    

        database.listOfItems().stream()
            .map(Item::getType)
            .distinct()
            .sorted()
            .forEach(System.out::println);

    }
}

