/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.TreeSet;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) {
        Database database1 = new Database(100);

        database1.listOfItems().stream()
                .collect(Collectors.toCollection(ArrayList::new));

        database1.listOfItems().stream()
                .collect(Collectors.groupingBy(Item::getType, Collectors.counting()))
                .forEach((k, v) -> System.out.println(k + ": " + v));

        database1.listOfItems().stream()
                .collect(Collectors.groupingBy(Item::getType, LinkedHashMap::new, Collectors.counting()))
                .forEach((k, v) -> System.out.println(k + ": " + v));

        var database = new Database(10);
        var history = new History(database);

        history.register(1L);
        history.register(2L);
        history.register(3L);
        history.register(4L);
        history.register(5L);
        history.register(1L);
        history.register(6L);
        history.register(7L);

        history.listVisualizedItems();

    }
}
