/*
 * This source file was generated by the Gradle 'init' task
 */
package com.felipegardin;

import java.math.BigDecimal;
import java.util.List;

import com.felipegardin.database.Database;
import com.felipegardin.model.Categoria;
import com.felipegardin.model.ItemCardapio;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Database database = new Database();

        ItemCardapio novoItem = ItemCardapio.builder()
                .nome("Pudim de Leite")
                .descricao("Pudim cremoso de leite condensado")
                .categoria(Categoria.SOBREMESA)
                .preco(new BigDecimal("14.90"))
                .build();

        database.add(novoItem);
        
        System.out.println("-----last item----");
        System.out.println(database.getLastRegister().get());

        List<ItemCardapio> elements = database.getAll();

        System.out.println("----total----");
        System.out.println("Total by database: " + database.count());
        System.out.println("Total of the list: " + elements.size());
    }
}
