/*
 * This source file was generated by the Gradle 'init' task
 */
package com.felipegardin;

import com.felipegardin.database.Database;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());

        Database database = new Database();

        System.out.println(database.getAll());
    }
}
